# Netlify configuration file

# Build settings (optional, often inferred by Netlify)
# [build]
#  command = "npm run build"
#  publish = "dist"

# Redirect rule for Single Page Applications (SPAs)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 